python preprocess.py \
        -train_src codc_data/dialog/dialog.train.5ref.txt \
        -train_tgt codc_data/ground/desc.train.5ref.txt \
        -valid_src codc_data/dialog/dialog.valid.5ref.txt \
        -valid_tgt codc_data/ground/desc.valid.5ref.txt \
        -save_data dataset/train_baseline \
        -src_seq_length 10000 \
        -tgt_seq_length 10000 \
        -src_seq_length_trunc 200 \
        -tgt_seq_length_trunc 15 \
        -dynamic_dict \
        -share_vocab \
        -shard_size 500000 \
        -src_vocab_size 20000 \
        -tgt_vocab_size 20000 \
        -overwrite